version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx configuration file

python:
  install:
    - method: pip
      path: .  # If your repository contains a Python package, install it
    - requirements: docs/requirements.txt  # Install additional dependencies